### ISSUE TITLE
Support for webpack@4

### ISSUE THREAD

**Issue by 4esnog** [aruntk/wc-loader#32]
Seems like wc-loader is incompatible with webpack@4

Here is the output of webpack build:
```
ERROR in ./assets/web-components/tags-select/tags-select.html
Module build failed: TypeError: Cannot read property 'output' of undefined
    at Object.convertPlaceholder (/Users/nchesnokov/tv-projects/data-issues/node_modules/wc-loader/dist/index.js:370:96)
    at Object.module.exports (/Users/nchesnokov/tv-projects/data-issues/node_modules/wc-loader/dist/index.js:434:22)
 @ ./assets/web-components/tags-select/tags-select.js 1:0-60
 @ ./assets/entries/report/report.js
```

**Comment by PratapDessai** [comment]
yes.. this is failing in webpack 4.  As per demo, webpack version is 3.
anyone looking into this?
